version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=tropical-express
      - POSTGRES_USER=josill
      - POSTGRES_PASSWORD=Strong@Password1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5267:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=tropical-express;Username=postgres;Password=Strong@Password1
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data:
