services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong@Password1
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5267:8080"
    depends_on:
      - sqlserver
    environment:
      - DefaultConnection=Server=sqlserver;Database=tropical-express;User Id=sa;Password=Strong@Password1;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sqlserver_data:
