// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TropicalExpress.Infrastructure;

#nullable disable

namespace TropicalExpress.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241012101458_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TropicalExpress.Domain.Fruit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("NetWeight", "TropicalExpress.Domain.Fruit.NetWeight#NetWeight", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Weight", "TropicalExpress.Domain.Fruit.NetWeight#NetWeight.Weight#Weight", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric");

                                    b2.Property<int>("WeightUnit")
                                        .HasColumnType("integer");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Fruits");
                });
#pragma warning restore 612, 618
        }
    }
}
