// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TropicalExpress.Infrastructure;

#nullable disable

namespace TropicalExpress.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241014105950_OwnedTypes")]
    partial class OwnedTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TropicalExpress.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TropicalExpress.Domain.Order", b =>
                {
                    b.OwnsMany("TropicalExpress.Domain.Fruit", "Fruits", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("FruitType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FruitType");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("Fruit");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("TropicalExpress.Domain.NetWeight", "NetWeight", b2 =>
                                {
                                    b2.Property<Guid>("FruitId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("FruitId");

                                    b2.ToTable("Fruit");

                                    b2.WithOwner()
                                        .HasForeignKey("FruitId");

                                    b2.OwnsOne("TropicalExpress.Domain.Weight", "Weight", b3 =>
                                        {
                                            b3.Property<Guid>("NetWeightFruitId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("Comment")
                                                .HasColumnType("text")
                                                .HasColumnName("NetWeightComment");

                                            b3.Property<int>("Unit")
                                                .HasColumnType("integer")
                                                .HasColumnName("NetWeightUnit");

                                            b3.Property<decimal>("Value")
                                                .HasColumnType("numeric")
                                                .HasColumnName("NetWeightValue");

                                            b3.HasKey("NetWeightFruitId");

                                            b3.ToTable("Fruit");

                                            b3.WithOwner()
                                                .HasForeignKey("NetWeightFruitId");
                                        });

                                    b2.Navigation("Weight")
                                        .IsRequired();
                                });

                            b1.Navigation("NetWeight")
                                .IsRequired();
                        });

                    b.Navigation("Fruits");
                });
#pragma warning restore 612, 618
        }
    }
}
