// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TropicalExpress.Infrastructure;

#nullable disable

namespace TropicalExpress.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TropicalExpress.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Fruit", "TropicalExpress.Domain.Order.Fruit#Fruit", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("NetWeight", "TropicalExpress.Domain.Order.Fruit#Fruit.NetWeight#NetWeight", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.ComplexProperty<Dictionary<string, object>>("Weight", "TropicalExpress.Domain.Order.Fruit#Fruit.NetWeight#NetWeight.Weight#Weight", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("Comment")
                                                .HasColumnType("text");

                                            b3.Property<int>("Unit")
                                                .HasColumnType("integer");

                                            b3.Property<decimal>("Value")
                                                .HasColumnType("numeric");
                                        });
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
